{
	"version": 1502710266,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundo-sheet0.png",
		"images/placa-sheet0.png",
		"images/sprite-sheet0.png",
		"images/cavalo-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/macaco-sheet0.png",
		"images/banana-sheet0.png",
		"images/manga-sheet0.png",
		"images/goiaba-sheet0.png",
		"images/celular-sheet0.png",
		"images/martelo-sheet0.png",
		"images/carro-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/yes-sheet0.png",
		"images/no-sheet0.png",
		"images/opcoes-sheet0.png",
		"images/ipontuacao-sheet0.png",
		"images/sfpontuacao.png",
		"media/219816__saraonsins__monkey-scream.m4a",
		"media/337816__blukotek__hammer-v1.m4a",
		"media/339838_gnimpl_mhm (online-audio-converter.com).m4a",
		"media/hum (online-audio-converter.com).m4a",
		"media/hum (online-audio-converter.com).ogg",
		"media/368592_doggo-mcdoggo_mmmm (online-audio-converter.com) (1).m4a",
		"media/368592_doggo-mcdoggo_mmmm (online-audio-converter.com) (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}