{
	"version": 1504531005,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundo-sheet0.png",
		"images/fundoceu-sheet0.png",
		"images/nuvem1-sheet0.png",
		"images/mato-sheet0.png",
		"images/arvore-sheet0.png",
		"images/caixa-sheet0.png",
		"images/caixa2-sheet0.png",
		"images/palha-sheet0.png",
		"images/agua1-sheet0.png",
		"images/agua2-sheet0.png",
		"images/agua3-sheet0.png",
		"images/agua4-sheet0.png",
		"images/agua5-sheet0.png",
		"images/agua6-sheet0.png",
		"images/pato-sheet0.png",
		"images/pedra-sheet0.png",
		"images/letf-sheet0.png",
		"images/leto-sheet0.png",
		"images/letn-sheet0.png",
		"images/letk-sheet0.png",
		"images/leti-sheet0.png",
		"images/letd-sheet0.png",
		"images/lets-sheet0.png",
		"images/sol-sheet0.png",
		"images/nuvem-sheet0.png",
		"images/fazendeiro-sheet0.png",
		"images/caixadeop-sheet0.png",
		"images/cerca1-sheet0.png",
		"images/maçã-sheet0.png",
		"images/cenoura-sheet0.png",
		"images/laranja-sheet0.png",
		"images/cerca2-sheet0.png",
		"images/sapo-sheet0.png",
		"images/chão-sheet0.png",
		"images/galinha-sheet0.png",
		"images/galinha-sheet1.png",
		"images/catavento-sheet0.png",
		"images/elice-sheet0.png",
		"images/placplay-sheet0.png",
		"images/play-sheet0.png",
		"images/placseta-sheet0.png",
		"images/bopcoes-sheet0.png",
		"images/ihudopcoes-sheet0.png",
		"images/ihudpause-sheet0.png",
		"images/bfechar-sheet0.png",
		"images/breiniciar-sheet0.png",
		"images/ipontuacao-sheet0.png",
		"images/sfpontuacao.png",
		"images/lama-sheet0.png",
		"images/porco-sheet0.png",
		"images/porco-sheet1.png",
		"images/milho-sheet0.png",
		"images/fudolayinic-sheet0.png",
		"images/logo-sheet0.png",
		"images/beijo-sheet0.png",
		"images/opção-sheet0.png",
		"images/fundopc-sheet0.png",
		"images/mens-sheet0.png",
		"images/inf-sheet0.png",
		"images/balao-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/caju-sheet0.png",
		"images/melancia-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/spritefont.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite25-sheet0.png",
		"media/174615_yottasounds_pig002 (online-audio-converter.com) (1).m4a",
		"media/174615_yottasounds_pig002 (online-audio-converter.com) (1).ogg",
		"media/316920_rudmer-rotteveel_chicken-single-alarm-call (online-audio-converter.com).m4a",
		"media/316920_rudmer-rotteveel_chicken-single-alarm-call (online-audio-converter.com).ogg",
		"media/166144__adam-n__kiss-07.m4a",
		"media/166144__adam-n__kiss-07.ogg",
		"media/click1.m4a",
		"media/click1.ogg",
		"media/phaserdown3 (online-audio-converter.com).m4a",
		"media/phaserdown3 (online-audio-converter.com).ogg",
		"media/powerup10 (online-audio-converter.com).m4a",
		"media/powerup10 (online-audio-converter.com).ogg",
		"media/58277__benboncan__cow.m4a",
		"media/58277__benboncan__cow.ogg",
		"media/242664__reitanna__quack.m4a",
		"media/242664__reitanna__quack.ogg",
		"media/51743__erkanozan__applause.m4a",
		"media/277020__sandermotions__applause-3.m4a",
		"media/277020__sandermotions__applause-3.ogg",
		"media/51743_erkanozan_applause (online-audio-converter.com).m4a",
		"media/51743_erkanozan_applause (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}